In [1]:
# Лабораторна робота 1
# Вступ до машинного навчання. Елементи лінійної алгебри.

# Завдання 1.
# Створіть одновимірний масив (вектор) зі зворотнім порядком перших 10 натуральних чисел та виведіть його значення.

import numpy as np

arr = np.arange(1, 11)

arr_reversed = arr[::-1]

print("Одновимірний масив:", arr_reversed)

Одновимірний масив: [10  9  8  7  6  5  4  3  2  1]


In [2]:
# Завдання 2.
# Створіть двовимірний масив (матрицю) розміром 3x3,
# заповніть його послідовністю чисел, де кожне наступне число менше попереднього на 3,
# та виведіть його значення.

import numpy as np

start = 100

seq = np.arange(start, start - 9*3, -3)

matrix = seq.reshape(3, 3)

print("Матриця 3x3:")
print(matrix)

Матриця 3x3:
[[100  97  94]
 [ 91  88  85]
 [ 82  79  76]]


In [3]:
# Завдання 3.
# Створіть масив розміром 3x3, заповніть його випадковими дійсними числами від 0 до 1 та виведіть його значення.

import numpy as np

matrix = np.random.rand(3, 3)

print("Матриця 3x3 з випадковими числами:")
print(matrix)

Матриця 3x3 з випадковими числами:
[[0.51542053 0.69818631 0.57647019]
 [0.18465354 0.45088805 0.80262162]
 [0.91931468 0.90435124 0.44296179]]


In [4]:
# Завдання 4.
# Створіть масив розміром 3x3, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та обчисліть добуток всіх елементів.

import numpy as np

matrix = np.random.rand(3, 3)
product = np.prod(matrix)

print("Матриця 3x3:")
print(matrix)
print("Добуток усіх елементів:", product)

Матриця 3x3:
[[0.02626918 0.18422435 0.495019  ]
 [0.9993113  0.0263531  0.41999673]
 [0.01685948 0.27393706 0.43842383]]
Добуток усіх елементів: 5.3651613725086986e-08


In [5]:
# Завдання 5.
# Створіть два одновимірних масиви розміром 6, заповніть їх випадковими цілими числами в діапазоні від -20 до 20
# та виконайте на них поелементні операції додавання, віднімання та множення.

import numpy as np

a = np.random.randint(-20, 21, 6)
b = np.random.randint(-20, 21, 6)

print("Масив A:", a)
print("Масив B:", b)

print("A + B:", a + b)
print("A - B:", a - b)
print("A * B:", a * b)

Масив A: [-10   1  -8   5 -12 -16]
Масив B: [-7 -2 10  6 -1  7]
A + B: [-17  -1   2  11 -13  -9]
A - B: [ -3   3 -18  -1 -11 -23]
A * B: [  70   -2  -80   30   12 -112]


In [6]:
# Завдання 6.
# Створіть дві матриці 2x2, заповніть їх довільними цілими числами від 6 до 10 та знайдіть їх добуток.

import numpy as np

A = np.random.randint(6, 11, (2, 2))
B = np.random.randint(6, 11, (2, 2))
C = np.dot(A, B)

print("Матриця A:")
print(A)
print("Матриця B:")
print(B)
print("Добуток A * B:")
print(C)

Матриця A:
[[10  6]
 [ 7  6]]
Матриця B:
[[10  7]
 [ 6 10]]
Добуток A * B:
[[136 130]
 [106 109]]


In [7]:
# Завдання 7.
# Створіть дві матриці розміром 3x2 та 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 8 та перемножте їх між собою.

import numpy as np

A = np.random.randint(1, 9, (3, 2))
B = np.random.randint(1, 9, (2, 2))
C = np.dot(A, B)

print("Матриця A (3x2):")
print(A)
print("Матриця B (2x2):")
print(B)
print("Добуток A * B (3x2 * 2x2 = 3x2):")
print(C)

Матриця A (3x2):
[[5 3]
 [1 1]
 [1 3]]
Матриця B (2x2):
[[4 4]
 [8 3]]
Добуток A * B (3x2 * 2x2 = 3x2):
[[44 29]
 [12  7]
 [28 13]]


In [8]:
# Завдання 8.
# Створіть матрицю розміром 2x2, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

import numpy as np

A = np.random.randint(1, 11, (2, 2))
inv_A = np.linalg.inv(A)

print("Матриця A:")
print(A)
print("Обернена матриця A⁻¹:")
print(inv_A)

Матриця A:
[[8 8]
 [9 7]]
Обернена матриця A⁻¹:
[[-0.4375  0.5   ]
 [ 0.5625 -0.5   ]]


In [9]:
# Завдання 9.
# Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 0 до 1 та транспонуйте її.

import numpy as np

A = np.random.randint(0, 2, (3, 3))
AT = A.T

print("Матриця A:")
print(A)
print("Транспонована матриця Aᵀ:")
print(AT)

Матриця A:
[[1 1 1]
 [0 1 0]
 [1 0 1]]
Транспонована матриця Aᵀ:
[[1 0 1]
 [1 1 0]
 [1 0 1]]


In [10]:
# Завдання 10.
# Створіть матрицю розміром 3x4 та вектор розміром 4x1, заповніть матрицю випадковими дійсними числами від 0 до 1,
# а вектор - випадковими цілими числами в діапазоні від 1 до 10, і знайдіть добуток матриці на вектор.

import numpy as np

A = np.random.rand(3, 4)
v = np.random.randint(1, 11, (4, 1))
result = np.dot(A, v)

print("Матриця A (3x4):")
print(A)
print("Вектор v (4x1):")
print(v)
print("Добуток A * v (3x1):")
print(result)

Матриця A (3x4):
[[0.93077324 0.95960099 0.60460839 0.21165624]
 [0.14022559 0.78727148 0.91884627 0.92876737]
 [0.76368111 0.48832329 0.94594438 0.17972533]]
Вектор v (4x1):
[[6]
 [9]
 [7]
 [3]]
Добуток A * v (3x1):
[[19.08827579]
 [17.14502286]
 [16.13778291]]


In [11]:
# Завдання 11.
# Створіть матрицю розміром 2x3 та вектор розміром 3x1, заповніть матрицю випадковими цілими числами в діапазоні від 1 до 10,
# а вектор - випадковими цілими числами в діапазоні від 1 до 10, і знайдіть добуток матриці на вектор.

import numpy as np

A = np.random.randint(1, 11, (2, 3))
v = np.random.randint(1, 11, (3, 1))
result = np.dot(A, v)

print("Матриця A (2x3):")
print(A)
print("Вектор v (3x1):")
print(v)
print("Добуток A * v (2x1):")
print(result)

Матриця A (2x3):
[[ 8  6  9]
 [10  2  5]]
Вектор v (3x1):
[[1]
 [5]
 [7]]
Добуток A * v (2x1):
[[101]
 [ 55]]


In [12]:
# Завдання 12.
# Створіть дві матриці розміром 6x6, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню суму.

import numpy as np

A = np.random.randint(1, 11, (6, 6))
B = np.random.randint(1, 11, (6, 6))
C = A + B

print("Матриця A:")
print(A)
print("Матриця B:")
print(B)
print("Сума матриць A + B:")
print(C)

Матриця A:
[[ 9  7  7  8  3  6]
 [ 7  3  4  9  7  4]
 [ 6  8  5  5 10  6]
 [ 7  7  4  9  4  1]
 [ 7  6  1  4  3  2]
 [ 9  7  7  7  8  8]]
Матриця B:
[[ 4  3 10  8  3  6]
 [ 5  9 10  1  4 10]
 [10  1  6  2  4  9]
 [ 3  2 10  9  6  5]
 [ 5  1  9  2  2  6]
 [ 3  8  3  4  5  6]]
Сума матриць A + B:
[[13 10 17 16  6 12]
 [12 12 14 10 11 14]
 [16  9 11  7 14 15]
 [10  9 14 18 10  6]
 [12  7 10  6  5  8]
 [12 15 10 11 13 14]]


In [13]:
# Завдання 13.
# Створіть дві матриці розміром 6x6, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть різницю їх елементів.

import numpy as np

A = np.random.rand(6, 6)
B = np.random.rand(6, 6)
C = A - B

print("Матриця A:")
print(A)
print("Матриця B:")
print(B)
print("Різниця матриць A - B:")
print(C)

Матриця A:
[[0.80934401 0.55362229 0.44397338 0.01081127 0.07315661 0.30379723]
 [0.89546439 0.2272913  0.78984837 0.54606339 0.17182426 0.1952504 ]
 [0.24418608 0.57914127 0.40045519 0.8739259  0.93357339 0.32195001]
 [0.95915325 0.63911433 0.51832    0.85362329 0.28803391 0.47093046]
 [0.85032015 0.21842551 0.87282414 0.83548183 0.88855262 0.79121642]
 [0.70672917 0.30730692 0.14556579 0.43168226 0.20632233 0.17534991]]
Матриця B:
[[0.71150751 0.23694317 0.53662248 0.44169974 0.67193113 0.58190085]
 [0.627253   0.8700149  0.65159735 0.84675923 0.83014594 0.94015906]
 [0.23264556 0.17379615 0.00467822 0.7226076  0.8712582  0.11256845]
 [0.2187662  0.84071533 0.59346655 0.58605451 0.38109647 0.28320753]
 [0.16593926 0.00549396 0.9997407  0.29783727 0.46691307 0.91164912]
 [0.55559476 0.74040689 0.2438693  0.0316062  0.29938762 0.19917094]]
Різниця матриць A - B:
[[ 0.0978365   0.31667911 -0.0926491  -0.43088847 -0.59877452 -0.27810362]
 [ 0.26821139 -0.64272359  0.13825102 -0.30069584 

In [14]:
# Завдання 14.
# Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від -5 до 5 та знайдіть добуток елементів матриці.

import numpy as np

A = np.random.uniform(-5, 5, (3, 3))
product = np.prod(A)

print("Матриця A:")
print(A)
print("Добуток елементів матриці:", product)

Матриця A:
[[ 0.46150433 -4.03933037  1.22763257]
 [ 3.83365213  3.87470672 -0.87976864]
 [-3.18413679  4.25549481  1.12945617]]
Добуток елементів матриці: -457.70403028687895


In [15]:
# Завдання 15.
# Створіть матрицю розміром 7x7, заповніть її випадковими дійсними числами в діапазоні від 0 до 1
# та знайдіть вектор-стовпчик, що містить найбільший елемент у кожному рядку матриці.

import numpy as np

A = np.random.rand(7, 7)
max_in_rows = np.max(A, axis=1).reshape(7, 1)

print("Матриця A:")
print(A)
print("Вектор-стовпчик найбільших елементів у рядках:")
print(max_in_rows)

Матриця A:
[[0.99234666 0.41153226 0.762894   0.7883169  0.43874354 0.13432824
  0.41202892]
 [0.60393815 0.26603307 0.89749179 0.36437422 0.89947225 0.66413208
  0.97499025]
 [0.72674889 0.3643599  0.8920159  0.5911413  0.29707801 0.67069029
  0.30101362]
 [0.8367839  0.86460516 0.39054117 0.46526082 0.54384224 0.62491499
  0.78053103]
 [0.78621733 0.24633745 0.30786623 0.4138666  0.35502561 0.76664639
  0.50729613]
 [0.86691681 0.50893525 0.07729166 0.1870507  0.79725722 0.8526869
  0.03145727]
 [0.10739212 0.28496703 0.94903911 0.06305917 0.02489365 0.91479705
  0.33695403]]
Вектор-стовпчик найбільших елементів у рядках:
[[0.99234666]
 [0.97499025]
 [0.8920159 ]
 [0.86460516]
 [0.78621733]
 [0.86691681]
 [0.94903911]]
